package encoding;

import java.io.UnsupportedEncodingException;
import java.util.List;

import com.alibaba.fastjson.JSON;

import models.t_user_address_list;
import play.Logger;
import play.db.jpa.JPA;
import utils.Base64;
import utils.JSONUtils;

public class Base64Test {
//WwogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1NTUxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1MTIxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYXZpZCBUYXlsb3IiLAogICAgIm1vYmlsZSIgOiAiNTU1NjEwNjY3OSIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNTU1NDc4NzY3MiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1NTI3MCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1MzUxNCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNTU1NzY2NDgyMyIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNzA3NTU1MTg1NCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJLYXRlIEJlbGwiLAogICAgIm1vYmlsZSIgOiAiNTU1NTY0ODU4MyIKICB9LAogIHsKICAgICJuYW1lIiA6ICJLYXRlIEJlbGwiLAogICAgIm1vYmlsZSIgOiAiNDE1NTU1MzY5NSIKICB9LAogIHsKICAgICJuYW1lIiA6ICJBbm5hIEhhcm8iLAogICAgIm1vYmlsZSIgOiAiNTU1NTIyODI0MyIKICB9Cl0=
//WwogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1NTUxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1MTIxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYXZpZCBUYXlsb3IiLAogICAgIm1vYmlsZSIgOiAiNTU1NjEwNjY3OSIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNTU1NDc4NzY3MiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1NTI3MCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1MzUxNCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNTU1NzY2NDgyMyIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNzA3NTU1MTg1NCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJLYXRlKyBCZWxsLSIsCiAgICAibW9iaWxlIiA6ICI1NTU1NjQ4NTgzIgogIH0sCiAgewogICAgIm5hbWUiIDogIkthdGUrIEJlbGwtIiwKICAgICJtb2JpbGUiIDogIjQxNTU1NTM2OTUiCiAgfSwKICB7CiAgICAibmFtZSIgOiAiQW5uYSogSGFyby8iLAogICAgIm1vYmlsZSIgOiAiNTU1NTIyODI0MyIKICB9Cl0=

//QmFzZTY05piv5LiA56eN6IO95bCG5Lu75oSPQmluYXJ56LWE5paZ55SoNjTnp43lrZflhYPnu4TlkIjmiJDlrZfkuLLnmoTmlrnms5XvvIzogIzov5nkuKpCaW5hcnnotYTmlpnlkozlrZfkuLLotYTmlpnlvbzmraTkuYvpl7TmmK/lj6/ku6XkupLnm7jovazmjaLnmoTvvIzljYHliIbmlrnkvr/jgILlnKjlrp7pmYXlupTnlKjkuIrvvIxCYXNlNjTpmaTkuobog73lsIZCaW5hcnnotYTmlpnlj6/op4bljJbkuYvlpJbvvIzkuZ/luLjnlKjmnaXooajnpLrlrZfkuLLliqDlr4bov4flkI7nmoTlhoXlrrnjgILlpoLmnpzopoHkvb/nlKhKYXZhIOeoi+W8j+ivreiogOadpeWunuS9nEJhc2U2NOeahOe8lueggeS4juino+eggeWKn+iDve+8jOWPr+S7peWPguiAg+acrOevh+aWh+eroOeahOS9nOazleOAgg==
//QmFzZTY05piv5LiA56eN6IO95bCG5Lu75oSPQmluYXJ56LWE5paZ55SoNjTnp43lrZflhYPnu4TlkIjmiJDlrZfkuLLnmoTmlrnms5XvvIzogIzov5nkuKpCaW5hcnnotYTmlpnlkozlrZfkuLLotYTmlpnlvbzmraTkuYvpl7TmmK/lj6/ku6XkupLnm7jovazmjaLnmoTvvIzljYHliIbmlrnkvr/jgILlnKjlrp7pmYXlupTnlKjkuIrvvIxCYXNlNjTpmaTkuobog73lsIZCaW5hcnnotYTmlpnlj6/op4bljJbkuYvlpJbvvIzkuZ/luLjnlKjmnaXooajnpLrlrZfkuLLliqDlr4bov4flkI7nmoTlhoXlrrnjgILlpoLmnpzopoHkvb/nlKhKYXZhIOeoi+W8j+ivreiogOadpeWunuS9nEJhc2U2NOeahOe8lueggeS4juino+eggeWKn+iDve+8jOWPr+S7peWPguiAg+acrOevh+aWh+eroOeahOS9nOazleOAgg==
/*pastrAddressList:W3sibmFtZSI6Iu-8iu-8iu-8gyXpq5jnuqfnu4_nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s
	eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjEyMzU4IDc5NiA1MDAifSx7Im5hbWUiOiIxMTIz
	55So5oi3IiwibW9iaWxlIjoiMTMxIDcyNTggODA4NiJ9LHsibmFtZSI6IueQieeSgzAwNCIsIm1v
	YmlsZSI6IjEzMSA3MjU4IDg4NTUifSx7Im5hbWUiOiLnkInnkoMwMDMiLCJtb2JpbGUiOiIxMzEg
	NzM2NyA2NDYzIn0seyJuYW1lIjoi55CJ55KDMDAxIiwibW9iaWxlIjoiMTMxIDczNjcgNjQ2OCJ9
	LHsibmFtZSI6IuWTiOWTiCIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjgifSx7Im5hbWUiOiLnkInn
	koMwMDIiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1lIjoi55CJ55KDMDA1IiwibW9i
	aWxlIjoiMTMxIDczNjcgNjQ2OSJ9LHsibmFtZSI6IueQieeSgzAwNiIsIm1vYmlsZSI6IjEzMTcy
	ODgwOTU5MyJ9LHsibmFtZSI6IjExMjPonJfniZsiLCJtb2JpbGUiOiIxMzY4NDU1NDY0NjQ2In0s
	eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjU1NDQ4ODY1ODg4ODgifV0=
*/	
	
	
	
	public static void main(String[] args) throws UnsupportedEncodingException {
		test1();
		
		
		String pastrAddressList="WwogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1NTUxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJKb2huJSBBcHBsZXNlZWQiLAogICAgIm1vYmlsZSIgOiAiODg4NTU1MTIxMiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYXZpZCBUYXlsb3IiLAogICAgIm1vYmlsZSIgOiAiNTU1NjEwNjY3OSIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNTU1NDc4NzY3MiIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1NTI3MCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJEYW5pZWwgSGlnZ2lucyBKci4iLAogICAgIm1vYmlsZSIgOiAiNDA4NTU1MzUxNCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNTU1NzY2NDgyMyIKICB9LAogIHsKICAgICJuYW1lIiA6ICJIYW5rIE0uIFpha3JvZmYiLAogICAgIm1vYmlsZSIgOiAiNzA3NTU1MTg1NCIKICB9LAogIHsKICAgICJuYW1lIiA6ICJLYXRlKyBCZWxsLSIsCiAgICAibW9iaWxlIiA6ICI1NTU1NjQ4NTgzIgogIH0sCiAgewogICAgIm5hbWUiIDogIkthdGUrIEJlbGwtIiwKICAgICJtb2JpbGUiIDogIjQxNTU1NTM2OTUiCiAgfSwKICB7CiAgICAibmFtZSIgOiAiQW5uYSogSGFyby8iLAogICAgIm1vYmlsZSIgOiAiNTU1NTIyODI0MyIKICB9Cl0=";

		//String pastrAddressList="QmFzZTY05piv5LiA56eN6IO95bCG5Lu75oSPQmluYXJ56LWE5paZ55SoNjTnp43lrZflhYPnu4TlkIjmiJDlrZfkuLLnmoTmlrnms5XvvIzogIzov5nkuKpCaW5hcnnotYTmlpnlkozlrZfkuLLotYTmlpnlvbzmraTkuYvpl7TmmK/lj6/ku6XkupLnm7jovazmjaLnmoTvvIzljYHliIbmlrnkvr/jgILlnKjlrp7pmYXlupTnlKjkuIrvvIxCYXNlNjTpmaTkuobog73lsIZCaW5hcnnotYTmlpnlj6/op4bljJbkuYvlpJbvvIzkuZ/luLjnlKjmnaXooajnpLrlrZfkuLLliqDlr4bov4flkI7nmoTlhoXlrrnjgILlpoLmnpzopoHkvb/nlKhKYXZhIOeoi+W8j+ivreiogOadpeWunuS9nEJhc2U2NOeahOe8lueggeS4juino+eggeWKn+iDve+8jOWPr+S7peWPguiAg+acrOevh+aWh+eroOeahOS9nOazleOAgg==";
/*
		String pastrAddressList="W3sibmFtZSI6Iu-8iu-8iu-8gyXpq5jnuqfnu4_nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s\r\n" + 
				"	eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjEyMzU4IDc5NiA1MDAifSx7Im5hbWUiOiIxMTIz\r\n" + 
				"	55So5oi3IiwibW9iaWxlIjoiMTMxIDcyNTggODA4NiJ9LHsibmFtZSI6IueQieeSgzAwNCIsIm1v\r\n" + 
				"	YmlsZSI6IjEzMSA3MjU4IDg4NTUifSx7Im5hbWUiOiLnkInnkoMwMDMiLCJtb2JpbGUiOiIxMzEg\r\n" + 
				"	NzM2NyA2NDYzIn0seyJuYW1lIjoi55CJ55KDMDAxIiwibW9iaWxlIjoiMTMxIDczNjcgNjQ2OCJ9\r\n" + 
				"	LHsibmFtZSI6IuWTiOWTiCIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjgifSx7Im5hbWUiOiLnkInn\r\n" + 
				"	koMwMDIiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1lIjoi55CJ55KDMDA1IiwibW9i\r\n" + 
				"	aWxlIjoiMTMxIDczNjcgNjQ2OSJ9LHsibmFtZSI6IueQieeSgzAwNiIsIm1vYmlsZSI6IjEzMTcy\r\n" + 
				"	ODgwOTU5MyJ9LHsibmFtZSI6IjExMjPonJfniZsiLCJtb2JpbGUiOiIxMzY4NDU1NDY0NjQ2In0s\r\n" + 
				"	eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjU1NDQ4ODY1ODg4ODgifV0=";*/
		pastrAddressList=new String(new com.alibaba.fastjson.util.Base64().decodeFast(pastrAddressList), "utf-8");//getUrlDecoder()
		System.out.println(pastrAddressList);
		
		String a="Base64是一种能将任意Binary资料用64种字元组合成字串的方法，而这个Binary资料和字串资料彼此之间是可以互相转换的，十分方便。在实际应用上，Base64除了能将Binary资料可视化之外，也常用来表示字串加密过后的内容。如果要使用Java 程式语言来实作Base64的编码与解码功能，可以参考本篇文章的作法。";
		
		System.out.println(new utils.Base64().encode(a.getBytes("utf-8")));
		
		
		
	}
	
	public static void test1() throws UnsupportedEncodingException {
		List<t_user_address_list> paramAddressList = null;
		try {
			paramAddressList=JSON.parseArray(null, t_user_address_list.class);
		}catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println(paramAddressList==null?"null":"not null");
		System.out.println(paramAddressList==null?"null":"not null");
		for(t_user_address_list paramList:paramAddressList) {
			System.out.println(paramList.name);
		}
		System.out.println(paramAddressList.size());
		
		String miw1="W3sibmFtZSI6Iu-8iu-8iu-8gyXpq5jnuqfnu4_nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s" + 
				"eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjEyMzU4IDc5NiA1MDAifSx7Im5hbWUiOiIxMTIz" + 
				"55So5oi3IiwibW9iaWxlIjoiMTMxIDcyNTggODA4NiJ9LHsibmFtZSI6IueQieeSgzAwNCIsIm1v" + 
				"YmlsZSI6IjEzMSA3MjU4IDg4NTUifSx7Im5hbWUiOiLnkInnkoMwMDMiLCJtb2JpbGUiOiIxMzEg" + 
				"NzM2NyA2NDYzIn0seyJuYW1lIjoi55CJ55KDMDAxIiwibW9iaWxlIjoiMTMxIDczNjcgNjQ2OCJ9" + 
				"LHsibmFtZSI6IuWTiOWTiCIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjgifSx7Im5hbWUiOiLnkInn" + 
				"koMwMDIiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1lIjoi55CJ55KDMDA1IiwibW9i" + 
				"aWxlIjoiMTMxIDczNjcgNjQ2OSJ9LHsibmFtZSI6IueQieeSgzAwNiIsIm1vYmlsZSI6IjEzMTcy" + 
				"ODgwOTU5MyJ9LHsibmFtZSI6IjExMjPonJfniZsiLCJtb2JpbGUiOiIxMzY4NDU1NDY0NjQ2In0s" + 
				"eyJuYW1lIjoiMTEyMzAwMSIsIm1vYmlsZSI6IjU1NDQ4ODY1ODg4ODgifV0=";
		String miw2="W3sibmFtZSI6Iu+8iu+8iu+8gyXpq5jnuqfnu4/nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s" + 
				"eyJuYW1lIjoi55CJ55KDMDA0IiwibW9iaWxlIjoiMTMxIDcyNTggODg1NSJ9LHsibmFtZSI6IueQ" + 
				"ieeSgzAwMyIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjMifSx7Im5hbWUiOiLnkInnkoMwMDEiLCJt" + 
				"b2JpbGUiOiIxMzEgNzM2NyA2NDY4In0seyJuYW1lIjoi5ZOI5ZOIIiwibW9iaWxlIjoiMTMxIDcz" + 
				"NjcgNjQ2OCJ9LHsibmFtZSI6IueQieeSgzAwMiIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjkifSx7" + 
				"Im5hbWUiOiLnkInnkoMwMDUiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1lIjoi55CJ" + 
				"55KDMDA2IiwibW9iaWxlIjoiMTMxNzI4ODA5NTkzIn1d";
		String miw3="W3sibmFtZSI6Iu-8iu-8iu-8gyXpq5jnuqfnu4_nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s" + 
				"eyJuYW1lIjoi55CJ55KDMDA0IiwibW9iaWxlIjoiMTMxIDcyNTggODg1NSJ9LHsibmFtZSI6IueQ" + 
				"ieeSgzAwMyIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjMifSx7Im5hbWUiOiLnkInnkoMwMDEiLCJt" + 
				"b2JpbGUiOiIxMzEgNzM2NyA2NDY4In0seyJuYW1lIjoi5ZOI5ZOIMTQjIiwibW9iaWxlIjoiMTMx" + 
				"IDczNjcgNjQ2OCJ9LHsibmFtZSI6IueQieeSgzAwMiIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0Njki" + 
				"fSx7Im5hbWUiOiLnkInnkoMwMDUiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1lIjoi" + 
				"55CJ55KDMDA2IiwibW9iaWxlIjoiMTMxNzI4ODA5NTkzIn1d";
		String miw4="W3sibmFtZSI6Iu+8iu+8iu+8gyXpq5jnuqfnu4/nkIYiLCJtb2JpbGUiOiJcL04qNzg5MysuIn0s" + 
				"eyJuYW1lIjoi55CJ55KDMDA0IiwibW9iaWxlIjoiMTMxIDcyNTggODg1NSJ9LHsibmFtZSI6IueQ" + 
				"ieeSgzAwMyIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0NjMifSx7Im5hbWUiOiLnkInnkoPljYXlubQi" + 
				"LCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY4In0seyJuYW1lIjoi5ZOI5ZOIMTQjIiwibW9iaWxlIjoi" + 
				"MTMxIDczNjcgNjQ2OCJ9LHsibmFtZSI6IueQieeSgzAwMiIsIm1vYmlsZSI6IjEzMSA3MzY3IDY0" + 
				"NjkifSx7Im5hbWUiOiLnkInnkoMwMDUiLCJtb2JpbGUiOiIxMzEgNzM2NyA2NDY5In0seyJuYW1l" + 
				"Ijoi55CJ55KDMDA2IiwibW9iaWxlIjoiMTMxNzI4ODA5NTkzIn1d";
		
		
		String minw1= new String(Base64.safeUrlDecode(miw4),"utf-8");
		System.out.println(minw1);
	}
}
