package models.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

import play.db.jpa.Model;

@Entity(name="migration_investment_bill_vo")
public class MigrationInvestmentBill implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.id
     * @mbg.generated
     */
	@Id
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.user_id
     * @mbg.generated
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.migration_investment_id
     * @mbg.generated
     */
    private Long migrationInvestmentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.bid_id
     * @mbg.generated
     */
    private Long bidId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.periods
     * @mbg.generated
     */
    private Byte periods;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.receive_time
     * @mbg.generated
     */
    private Date receiveTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.receive_corpus
     * @mbg.generated
     */
    private BigDecimal receiveCorpus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.receive_interest
     * @mbg.generated
     */
    private BigDecimal receiveInterest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.receive_increase_interest
     * @mbg.generated
     */
    private BigDecimal receiveIncreaseInterest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.is_receive_before
     * @mbg.generated
     */
    private Boolean isReceiveBefore;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.is_receive
     * @mbg.generated
     */
    private Boolean isReceive;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.real_receive_time
     * @mbg.generated
     */
    private Date realReceiveTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment_bill.version
     * @mbg.generated
     */
    private Integer version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table migration_investment_bill
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.id
     * @return  the value of migration_investment_bill.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.id
     * @param id  the value for migration_investment_bill.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.user_id
     * @return  the value of migration_investment_bill.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.user_id
     * @param userId  the value for migration_investment_bill.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.migration_investment_id
     * @return  the value of migration_investment_bill.migration_investment_id
     * @mbg.generated
     */
    public Long getMigrationInvestmentId() {
        return migrationInvestmentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.migration_investment_id
     * @param migrationInvestmentId  the value for migration_investment_bill.migration_investment_id
     * @mbg.generated
     */
    public void setMigrationInvestmentId(Long migrationInvestmentId) {
        this.migrationInvestmentId = migrationInvestmentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.bid_id
     * @return  the value of migration_investment_bill.bid_id
     * @mbg.generated
     */
    public Long getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.bid_id
     * @param bidId  the value for migration_investment_bill.bid_id
     * @mbg.generated
     */
    public void setBidId(Long bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.periods
     * @return  the value of migration_investment_bill.periods
     * @mbg.generated
     */
    public Byte getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.periods
     * @param periods  the value for migration_investment_bill.periods
     * @mbg.generated
     */
    public void setPeriods(Byte periods) {
        this.periods = periods;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.receive_time
     * @return  the value of migration_investment_bill.receive_time
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.receive_time
     * @param receiveTime  the value for migration_investment_bill.receive_time
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.receive_corpus
     * @return  the value of migration_investment_bill.receive_corpus
     * @mbg.generated
     */
    public BigDecimal getReceiveCorpus() {
        return receiveCorpus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.receive_corpus
     * @param receiveCorpus  the value for migration_investment_bill.receive_corpus
     * @mbg.generated
     */
    public void setReceiveCorpus(BigDecimal receiveCorpus) {
        this.receiveCorpus = receiveCorpus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.receive_interest
     * @return  the value of migration_investment_bill.receive_interest
     * @mbg.generated
     */
    public BigDecimal getReceiveInterest() {
        return receiveInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.receive_interest
     * @param receiveInterest  the value for migration_investment_bill.receive_interest
     * @mbg.generated
     */
    public void setReceiveInterest(BigDecimal receiveInterest) {
        this.receiveInterest = receiveInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.receive_increase_interest
     * @return  the value of migration_investment_bill.receive_increase_interest
     * @mbg.generated
     */
    public BigDecimal getReceiveIncreaseInterest() {
        return receiveIncreaseInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.receive_increase_interest
     * @param receiveIncreaseInterest  the value for migration_investment_bill.receive_increase_interest
     * @mbg.generated
     */
    public void setReceiveIncreaseInterest(BigDecimal receiveIncreaseInterest) {
        this.receiveIncreaseInterest = receiveIncreaseInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.is_receive_before
     * @return  the value of migration_investment_bill.is_receive_before
     * @mbg.generated
     */
    public Boolean getIsReceiveBefore() {
        return isReceiveBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.is_receive_before
     * @param isReceiveBefore  the value for migration_investment_bill.is_receive_before
     * @mbg.generated
     */
    public void setIsReceiveBefore(Boolean isReceiveBefore) {
        this.isReceiveBefore = isReceiveBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.is_receive
     * @return  the value of migration_investment_bill.is_receive
     * @mbg.generated
     */
    public Boolean getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.is_receive
     * @param isReceive  the value for migration_investment_bill.is_receive
     * @mbg.generated
     */
    public void setIsReceive(Boolean isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.real_receive_time
     * @return  the value of migration_investment_bill.real_receive_time
     * @mbg.generated
     */
    public Date getRealReceiveTime() {
        return realReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.real_receive_time
     * @param realReceiveTime  the value for migration_investment_bill.real_receive_time
     * @mbg.generated
     */
    public void setRealReceiveTime(Date realReceiveTime) {
        this.realReceiveTime = realReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment_bill.version
     * @return  the value of migration_investment_bill.version
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment_bill.version
     * @param version  the value for migration_investment_bill.version
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}