package models.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

import play.db.jpa.Model;

@Entity(name="migration_investment_vo")
public class MigrationInvestment implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.id
     * @mbg.generated
     */
	@Id
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.user_id
     * @mbg.generated
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.bid_id
     * @mbg.generated
     */
    private Long bidId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.bid_title
     * @mbg.generated
     */
    private String bidTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.repayment_type_id
     * @mbg.generated
     */
    private Long repaymentTypeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.period_unit
     * @mbg.generated
     */
    private Integer periodUnit;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.period
     * @mbg.generated
     */
    private Integer period;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.create_time
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.loan_time
     * @mbg.generated
     */
    private Date loanTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.apr
     * @mbg.generated
     */
    private BigDecimal apr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.is_increase_rate
     * @mbg.generated
     */
    private Boolean isIncreaseRate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.increase_rate
     * @mbg.generated
     */
    private Double increaseRate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.amount
     * @mbg.generated
     */
    private BigDecimal amount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.red_amount
     * @mbg.generated
     */
    private BigDecimal redAmount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.interest
     * @mbg.generated
     */
    private BigDecimal interest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.increase_interest
     * @mbg.generated
     */
    private BigDecimal increaseInterest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.is_finished
     * @mbg.generated
     */
    private Boolean isFinished;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.finished_time
     * @mbg.generated
     */
    private Date finishedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column migration_investment.version
     * @mbg.generated
     */
    private Integer version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table migration_investment
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.id
     * @return  the value of migration_investment.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.id
     * @param id  the value for migration_investment.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.user_id
     * @return  the value of migration_investment.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.user_id
     * @param userId  the value for migration_investment.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.bid_id
     * @return  the value of migration_investment.bid_id
     * @mbg.generated
     */
    public Long getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.bid_id
     * @param bidId  the value for migration_investment.bid_id
     * @mbg.generated
     */
    public void setBidId(Long bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.bid_title
     * @return  the value of migration_investment.bid_title
     * @mbg.generated
     */
    public String getBidTitle() {
        return bidTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.bid_title
     * @param bidTitle  the value for migration_investment.bid_title
     * @mbg.generated
     */
    public void setBidTitle(String bidTitle) {
        this.bidTitle = bidTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.repayment_type_id
     * @return  the value of migration_investment.repayment_type_id
     * @mbg.generated
     */
    public Long getRepaymentTypeId() {
        return repaymentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.repayment_type_id
     * @param repaymentTypeId  the value for migration_investment.repayment_type_id
     * @mbg.generated
     */
    public void setRepaymentTypeId(Long repaymentTypeId) {
        this.repaymentTypeId = repaymentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.period_unit
     * @return  the value of migration_investment.period_unit
     * @mbg.generated
     */
    public Integer getPeriodUnit() {
        return periodUnit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.period_unit
     * @param periodUnit  the value for migration_investment.period_unit
     * @mbg.generated
     */
    public void setPeriodUnit(Integer periodUnit) {
        this.periodUnit = periodUnit;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.period
     * @return  the value of migration_investment.period
     * @mbg.generated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.period
     * @param period  the value for migration_investment.period
     * @mbg.generated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.create_time
     * @return  the value of migration_investment.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.create_time
     * @param createTime  the value for migration_investment.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.loan_time
     * @return  the value of migration_investment.loan_time
     * @mbg.generated
     */
    public Date getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.loan_time
     * @param loanTime  the value for migration_investment.loan_time
     * @mbg.generated
     */
    public void setLoanTime(Date loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.apr
     * @return  the value of migration_investment.apr
     * @mbg.generated
     */
    public BigDecimal getApr() {
        return apr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.apr
     * @param apr  the value for migration_investment.apr
     * @mbg.generated
     */
    public void setApr(BigDecimal apr) {
        this.apr = apr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.is_increase_rate
     * @return  the value of migration_investment.is_increase_rate
     * @mbg.generated
     */
    public Boolean getIsIncreaseRate() {
        return isIncreaseRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.is_increase_rate
     * @param isIncreaseRate  the value for migration_investment.is_increase_rate
     * @mbg.generated
     */
    public void setIsIncreaseRate(Boolean isIncreaseRate) {
        this.isIncreaseRate = isIncreaseRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.increase_rate
     * @return  the value of migration_investment.increase_rate
     * @mbg.generated
     */
    public Double getIncreaseRate() {
        return increaseRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.increase_rate
     * @param increaseRate  the value for migration_investment.increase_rate
     * @mbg.generated
     */
    public void setIncreaseRate(Double increaseRate) {
        this.increaseRate = increaseRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.amount
     * @return  the value of migration_investment.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.amount
     * @param amount  the value for migration_investment.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.red_amount
     * @return  the value of migration_investment.red_amount
     * @mbg.generated
     */
    public BigDecimal getRedAmount() {
        return redAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.red_amount
     * @param redAmount  the value for migration_investment.red_amount
     * @mbg.generated
     */
    public void setRedAmount(BigDecimal redAmount) {
        this.redAmount = redAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.interest
     * @return  the value of migration_investment.interest
     * @mbg.generated
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.interest
     * @param interest  the value for migration_investment.interest
     * @mbg.generated
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.increase_interest
     * @return  the value of migration_investment.increase_interest
     * @mbg.generated
     */
    public BigDecimal getIncreaseInterest() {
        return increaseInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.increase_interest
     * @param increaseInterest  the value for migration_investment.increase_interest
     * @mbg.generated
     */
    public void setIncreaseInterest(BigDecimal increaseInterest) {
        this.increaseInterest = increaseInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.is_finished
     * @return  the value of migration_investment.is_finished
     * @mbg.generated
     */
    public Boolean getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.is_finished
     * @param isFinished  the value for migration_investment.is_finished
     * @mbg.generated
     */
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.finished_time
     * @return  the value of migration_investment.finished_time
     * @mbg.generated
     */
    public Date getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.finished_time
     * @param finishedTime  the value for migration_investment.finished_time
     * @mbg.generated
     */
    public void setFinishedTime(Date finishedTime) {
        this.finishedTime = finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column migration_investment.version
     * @return  the value of migration_investment.version
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column migration_investment.version
     * @param version  the value for migration_investment.version
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}